### ISSUE TITLE
HSL palette

### ISSUE THREAD

**Issue by jennschiffer** [make8bitart/make8bitart#18]
the current palette is technically not 8-bit anyway, so let's friggin go for it

**Comment by jennschiffer** [comment]
I'm going to put this as accepted. @incompl, this was your idea from forever ago so if you can find or make a pixelated hsl palette, that would be 💯

**Comment by incompl** [comment]
Just made one!

![hsls255](https://cloud.githubusercontent.com/assets/211047/6084625/9715e7f4-ae00-11e4-93a9-e2a68cf53ff0.png)

If you like it, how should it be integrated? I'm happy to submit a PR but I'd like to know your idea of how it should fit into the color pickers menu.

**Comment by jennschiffer** [comment]
if you wanna do a PR, make it 195px x 195px and convert to base 64 and replace the old image here: https://github.com/make8bitart/make8bitart/blob/master/js/app/make8bitart.js#L479

But also add the image to the assets directory as hsl-palette.png or whatever is readable :D

**Comment by incompl** [comment]
PR Here: #37
