### ISSUE TITLE
have color-picker on right-click

### ISSUE THREAD

**Issue by jennschiffer** [make8bitart/make8bitart#19]
Not sure how to let the user know this works if added, and if that will make the current dropper tool redundant? Maybe show the tool selected and deselected real quick on right-click?

**Comment by joshturner** [comment]
Alt/Option in Photoshop induces the eye dropper tool. Might be more intuitive to have keys mapped similarly to apps people already might use. Just a suggestion.

**Comment by jennschiffer** [comment]
:santa:

**Comment by incompl** [comment]
:egg:
