### ISSUE TITLE
Change image along with the pixel size

### ISSUE THREAD

**Issue by JRigotti** [make8bitart/make8bitart#26]
I don't think it's a bug, but I found weird the fact that after drawing something. If I change the pixel size, the image remains the same size, resulting in a "semi pixel".

I guess the expected behavior would the image resize to the new pixel size, acting like a zoom.

![Issue]
(http://i.imgur.com/T13Rt3U.png)

PS. Nice tool, having a great time playing with!

**Comment by jennschiffer** [comment]
creating a new issue for a "zoom" feature request
