### ISSUE TITLE
[notes] Imgur tags

### ISSUE THREAD

**Issue by brianloveswords** [make8bitart/make8bitart#39]
I did some research into this and found out that the API doesn't support tags because images can't have tags unless they are "Published" to Imgur (which is different than just uploading) and "publishing" isn't supported by the API (probably because it seems to require a specific user's account).

And the search definitely isn't great: I uploaded a few images with the title "make8bitart" and the search doesn't find those or any that would have been coming from here already.

The workaround I can see is creating a custom gallery and putting all images shared from this tool in that gallery.

**Comment by jennschiffer** [comment]
thanks for researching b-money! I'll create a new issue for going from tags to gallery and close this one. When I originally wrote this, there were definitely docs for tagging wompwomp
